//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDoarIncome
    {
        public int id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string CheshbonNo { get; set; }
        public string ReferanceNumber { get; set; }
        public string SnifNo { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string ValueDate { get; set; }
        public string ReferanceNumber2 { get; set; }
        public string MutavNo { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> ProcessingStatus { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> TransactionCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> BankDoarCommandType { get; set; }
        public string fileDoarName { get; set; }
    }
}
