//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int ProviderId { get; set; }
        public string EmailTo { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string EmailImportance { get; set; }
        public string EmailAttachments { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsSend { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
        public Nullable<int> EmailType { get; set; }
        public string ReportUrl { get; set; }
    }
}
