//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string TemplatePath { get; set; }
        public string ProcedureName { get; set; }
        public string NameEng { get; set; }
        public string Class { get; set; }
        public Nullable<int> SpecialRecipients { get; set; }
        public string TableName { get; set; }
        public string Params { get; set; }
        public string version { get; set; }
        public Nullable<bool> Header { get; set; }
        public Nullable<bool> Footer { get; set; }
        public Nullable<bool> UserSign { get; set; }
    }
}
