//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int MahozCode { get; set; }
        public int MashbashCode { get; set; }
        public int AtarCode { get; set; }
        public Nullable<int> ActiveWorkPlanId { get; set; }
        public Nullable<int> ActiveTenderId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string FranchiseeName { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> PrimeryContractId { get; set; }
        public int ProjectType { get; set; }
        public int HousingUnits { get; set; }
        public Nullable<int> MarketingMethodHousingUnits { get; set; }
        public Nullable<int> ReportedHousingUnits { get; set; }
        public int MarketingMethod { get; set; }
        public int DevelopmentMethod { get; set; }
        public string MmiNumber { get; set; }
        public bool IsRequiredSalesReports { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<System.DateTime> SalesReportingBeginDate { get; set; }
        public Nullable<System.DateTime> RecommendationExpiration { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public int Version { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> ConstructionProgressBeginDate { get; set; }
        public Nullable<bool> IsRequiredConstructionProgress { get; set; }
        public Nullable<int> MerkavaStatus { get; set; }
        public Nullable<System.DateTime> MerkavaStatusDate { get; set; }
        public Nullable<int> MerkavaInterfaceWbs { get; set; }
        public string WbsElement { get; set; }
        public Nullable<int> MerkavaStatusWbs { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsMerged { get; set; }
        public Nullable<bool> IsNeedManualLotsChanges { get; set; }
        public bool IsHeskemGag { get; set; }
        public Nullable<System.DateTime> FirstApartmentHandoverDate { get; set; }
        public Nullable<int> PublicHousingUnits { get; set; }
        public Nullable<int> EstimationNo { get; set; }
    }
}
