//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int Id { get; set; }
        public Nullable<int> MerkavaId { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> POB { get; set; }
        public string Email { get; set; }
        public string InternetPassword { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<int> MerkavaActiveType { get; set; }
        public string MerkavaRemark { get; set; }
    }
}
