//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderSection
    {
        public int Id { get; set; }
        public string Section { get; set; }
        public string ParentSection { get; set; }
        public string Text { get; set; }
        public Nullable<bool> ConditionId { get; set; }
        public Nullable<int> SectionsOrder { get; set; }
        public Nullable<int> Version { get; set; }
        public string Numerator { get; set; }
    }
}
