//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderBookletSection
    {
        public int Id { get; set; }
        public Nullable<int> TenderSectionId { get; set; }
        public int TenderId { get; set; }
        public string SectionNumber { get; set; }
        public string SectionBody { get; set; }
        public Nullable<int> versionBooklat { get; set; }
    }
}
