//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WEBAPIODATAV3.SPWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SPWebServiceSoap", Namespace="http://moch.gov.il/")]
    public partial class SPWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveItemByPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveItemNoTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActionsOnDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActionsOnDocumentsOldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReferenceNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsLocationExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentByQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewAtarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPropertiesToItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPathByQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsByCrossSiteQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDocLibrary1OperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDocLibraryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SPWebService() {
            this.Url = global::WEBAPIODATAV3.Properties.Settings.Default.WEBAPIODATAV3_SPWebService_SPWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event SaveItemCompletedEventHandler SaveItemCompleted;
        
        /// <remarks/>
        public event SaveItemByPathCompletedEventHandler SaveItemByPathCompleted;
        
        /// <remarks/>
        public event SaveItemNoTokenCompletedEventHandler SaveItemNoTokenCompleted;
        
        /// <remarks/>
        public event GetDocumentsCompletedEventHandler GetDocumentsCompleted;
        
        /// <remarks/>
        public event ActionsOnDocumentsCompletedEventHandler ActionsOnDocumentsCompleted;
        
        /// <remarks/>
        public event ActionsOnDocumentsOldCompletedEventHandler ActionsOnDocumentsOldCompleted;
        
        /// <remarks/>
        public event GetReferenceNumberCompletedEventHandler GetReferenceNumberCompleted;
        
        /// <remarks/>
        public event IsLocationExistsCompletedEventHandler IsLocationExistsCompleted;
        
        /// <remarks/>
        public event GetDocumentByQueryCompletedEventHandler GetDocumentByQueryCompleted;
        
        /// <remarks/>
        public event MoveFileCompletedEventHandler MoveFileCompleted;
        
        /// <remarks/>
        public event DeleteFileCompletedEventHandler DeleteFileCompleted;
        
        /// <remarks/>
        public event CreateNewAtarCompletedEventHandler CreateNewAtarCompleted;
        
        /// <remarks/>
        public event SetPropertiesToItemCompletedEventHandler SetPropertiesToItemCompleted;
        
        /// <remarks/>
        public event GetPathByQueryCompletedEventHandler GetPathByQueryCompleted;
        
        /// <remarks/>
        public event GetItemsByCrossSiteQueryCompletedEventHandler GetItemsByCrossSiteQueryCompleted;
        
        /// <remarks/>
        public event CreateDirectoryCompletedEventHandler CreateDirectoryCompleted;
        
        /// <remarks/>
        public event CreateDocLibrary1CompletedEventHandler CreateDocLibrary1Completed;
        
        /// <remarks/>
        public event CreateDocLibraryCompletedEventHandler CreateDocLibraryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/GetItems", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType GetItems(string path, string userName) {
            object[] results = this.Invoke("GetItems", new object[] {
                        path,
                        userName});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(string path, string userName) {
            this.GetItemsAsync(path, userName, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(string path, string userName, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        path,
                        userName}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/SaveItem", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType SaveItem(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            object[] results = this.Invoke("SaveItem", new object[] {
                        uploadPath,
                        filePath,
                        jsonPropFolder,
                        jsonPropFile,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void SaveItemAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            this.SaveItemAsync(uploadPath, filePath, jsonPropFolder, jsonPropFile, userCode, null);
        }
        
        /// <remarks/>
        public void SaveItemAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode, object userState) {
            if ((this.SaveItemOperationCompleted == null)) {
                this.SaveItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveItemOperationCompleted);
            }
            this.InvokeAsync("SaveItem", new object[] {
                        uploadPath,
                        filePath,
                        jsonPropFolder,
                        jsonPropFile,
                        userCode}, this.SaveItemOperationCompleted, userState);
        }
        
        private void OnSaveItemOperationCompleted(object arg) {
            if ((this.SaveItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveItemCompleted(this, new SaveItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/SaveItemByPath", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType SaveItemByPath(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            object[] results = this.Invoke("SaveItemByPath", new object[] {
                        uploadPath,
                        filePath,
                        jsonPropFolder,
                        jsonPropFile,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void SaveItemByPathAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            this.SaveItemByPathAsync(uploadPath, filePath, jsonPropFolder, jsonPropFile, userCode, null);
        }
        
        /// <remarks/>
        public void SaveItemByPathAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode, object userState) {
            if ((this.SaveItemByPathOperationCompleted == null)) {
                this.SaveItemByPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveItemByPathOperationCompleted);
            }
            this.InvokeAsync("SaveItemByPath", new object[] {
                        uploadPath,
                        filePath,
                        jsonPropFolder,
                        jsonPropFile,
                        userCode}, this.SaveItemByPathOperationCompleted, userState);
        }
        
        private void OnSaveItemByPathOperationCompleted(object arg) {
            if ((this.SaveItemByPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveItemByPathCompleted(this, new SaveItemByPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/SaveItemNoToken", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType SaveItemNoToken(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile) {
            object[] results = this.Invoke("SaveItemNoToken", new object[] {
                        uploadPath,
                        filePath,
                        jsonPropFolder,
                        jsonPropFile});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void SaveItemNoTokenAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile) {
            this.SaveItemNoTokenAsync(uploadPath, filePath, jsonPropFolder, jsonPropFile, null);
        }
        
        /// <remarks/>
        public void SaveItemNoTokenAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, object userState) {
            if ((this.SaveItemNoTokenOperationCompleted == null)) {
                this.SaveItemNoTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveItemNoTokenOperationCompleted);
            }
            this.InvokeAsync("SaveItemNoToken", new object[] {
                        uploadPath,
                        filePath,
                        jsonPropFolder,
                        jsonPropFile}, this.SaveItemNoTokenOperationCompleted, userState);
        }
        
        private void OnSaveItemNoTokenOperationCompleted(object arg) {
            if ((this.SaveItemNoTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveItemNoTokenCompleted(this, new SaveItemNoTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/GetDocuments", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType GetDocuments(string uploadPath, string queryStr, string viewFields, string userName) {
            object[] results = this.Invoke("GetDocuments", new object[] {
                        uploadPath,
                        queryStr,
                        viewFields,
                        userName});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentsAsync(string uploadPath, string queryStr, string viewFields, string userName) {
            this.GetDocumentsAsync(uploadPath, queryStr, viewFields, userName, null);
        }
        
        /// <remarks/>
        public void GetDocumentsAsync(string uploadPath, string queryStr, string viewFields, string userName, object userState) {
            if ((this.GetDocumentsOperationCompleted == null)) {
                this.GetDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentsOperationCompleted);
            }
            this.InvokeAsync("GetDocuments", new object[] {
                        uploadPath,
                        queryStr,
                        viewFields,
                        userName}, this.GetDocumentsOperationCompleted, userState);
        }
        
        private void OnGetDocumentsOperationCompleted(object arg) {
            if ((this.GetDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentsCompleted(this, new GetDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/ActionsOnDocuments", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType ActionsOnDocuments(Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields) {
            object[] results = this.Invoke("ActionsOnDocuments", new object[] {
                        method,
                        url,
                        queryStr,
                        userCode,
                        jsonPropFile,
                        viewFields});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void ActionsOnDocumentsAsync(Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields) {
            this.ActionsOnDocumentsAsync(method, url, queryStr, userCode, jsonPropFile, viewFields, null);
        }
        
        /// <remarks/>
        public void ActionsOnDocumentsAsync(Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields, object userState) {
            if ((this.ActionsOnDocumentsOperationCompleted == null)) {
                this.ActionsOnDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActionsOnDocumentsOperationCompleted);
            }
            this.InvokeAsync("ActionsOnDocuments", new object[] {
                        method,
                        url,
                        queryStr,
                        userCode,
                        jsonPropFile,
                        viewFields}, this.ActionsOnDocumentsOperationCompleted, userState);
        }
        
        private void OnActionsOnDocumentsOperationCompleted(object arg) {
            if ((this.ActionsOnDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActionsOnDocumentsCompleted(this, new ActionsOnDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/ActionsOnDocumentsOld", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType ActionsOnDocumentsOld(Method method, string url, string queryStr, string userCode, string jsonPropFile) {
            object[] results = this.Invoke("ActionsOnDocumentsOld", new object[] {
                        method,
                        url,
                        queryStr,
                        userCode,
                        jsonPropFile});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void ActionsOnDocumentsOldAsync(Method method, string url, string queryStr, string userCode, string jsonPropFile) {
            this.ActionsOnDocumentsOldAsync(method, url, queryStr, userCode, jsonPropFile, null);
        }
        
        /// <remarks/>
        public void ActionsOnDocumentsOldAsync(Method method, string url, string queryStr, string userCode, string jsonPropFile, object userState) {
            if ((this.ActionsOnDocumentsOldOperationCompleted == null)) {
                this.ActionsOnDocumentsOldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActionsOnDocumentsOldOperationCompleted);
            }
            this.InvokeAsync("ActionsOnDocumentsOld", new object[] {
                        method,
                        url,
                        queryStr,
                        userCode,
                        jsonPropFile}, this.ActionsOnDocumentsOldOperationCompleted, userState);
        }
        
        private void OnActionsOnDocumentsOldOperationCompleted(object arg) {
            if ((this.ActionsOnDocumentsOldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActionsOnDocumentsOldCompleted(this, new ActionsOnDocumentsOldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/GetReferenceNumber", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType GetReferenceNumber() {
            object[] results = this.Invoke("GetReferenceNumber", new object[0]);
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetReferenceNumberAsync() {
            this.GetReferenceNumberAsync(null);
        }
        
        /// <remarks/>
        public void GetReferenceNumberAsync(object userState) {
            if ((this.GetReferenceNumberOperationCompleted == null)) {
                this.GetReferenceNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceNumberOperationCompleted);
            }
            this.InvokeAsync("GetReferenceNumber", new object[0], this.GetReferenceNumberOperationCompleted, userState);
        }
        
        private void OnGetReferenceNumberOperationCompleted(object arg) {
            if ((this.GetReferenceNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReferenceNumberCompleted(this, new GetReferenceNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/IsLocationExists", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType IsLocationExists(string pathToCheck, string userName) {
            object[] results = this.Invoke("IsLocationExists", new object[] {
                        pathToCheck,
                        userName});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void IsLocationExistsAsync(string pathToCheck, string userName) {
            this.IsLocationExistsAsync(pathToCheck, userName, null);
        }
        
        /// <remarks/>
        public void IsLocationExistsAsync(string pathToCheck, string userName, object userState) {
            if ((this.IsLocationExistsOperationCompleted == null)) {
                this.IsLocationExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsLocationExistsOperationCompleted);
            }
            this.InvokeAsync("IsLocationExists", new object[] {
                        pathToCheck,
                        userName}, this.IsLocationExistsOperationCompleted, userState);
        }
        
        private void OnIsLocationExistsOperationCompleted(object arg) {
            if ((this.IsLocationExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsLocationExistsCompleted(this, new IsLocationExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/GetDocumentByQuery", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType GetDocumentByQuery(string uploadPath, string queryStr, string userName) {
            object[] results = this.Invoke("GetDocumentByQuery", new object[] {
                        uploadPath,
                        queryStr,
                        userName});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentByQueryAsync(string uploadPath, string queryStr, string userName) {
            this.GetDocumentByQueryAsync(uploadPath, queryStr, userName, null);
        }
        
        /// <remarks/>
        public void GetDocumentByQueryAsync(string uploadPath, string queryStr, string userName, object userState) {
            if ((this.GetDocumentByQueryOperationCompleted == null)) {
                this.GetDocumentByQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentByQueryOperationCompleted);
            }
            this.InvokeAsync("GetDocumentByQuery", new object[] {
                        uploadPath,
                        queryStr,
                        userName}, this.GetDocumentByQueryOperationCompleted, userState);
        }
        
        private void OnGetDocumentByQueryOperationCompleted(object arg) {
            if ((this.GetDocumentByQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentByQueryCompleted(this, new GetDocumentByQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/MoveFile", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType MoveFile(string filepath, string despath) {
            object[] results = this.Invoke("MoveFile", new object[] {
                        filepath,
                        despath});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void MoveFileAsync(string filepath, string despath) {
            this.MoveFileAsync(filepath, despath, null);
        }
        
        /// <remarks/>
        public void MoveFileAsync(string filepath, string despath, object userState) {
            if ((this.MoveFileOperationCompleted == null)) {
                this.MoveFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveFileOperationCompleted);
            }
            this.InvokeAsync("MoveFile", new object[] {
                        filepath,
                        despath}, this.MoveFileOperationCompleted, userState);
        }
        
        private void OnMoveFileOperationCompleted(object arg) {
            if ((this.MoveFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveFileCompleted(this, new MoveFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/DeleteFile", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType DeleteFile(string filePath) {
            object[] results = this.Invoke("DeleteFile", new object[] {
                        filePath});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFileAsync(string filePath) {
            this.DeleteFileAsync(filePath, null);
        }
        
        /// <remarks/>
        public void DeleteFileAsync(string filePath, object userState) {
            if ((this.DeleteFileOperationCompleted == null)) {
                this.DeleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileOperationCompleted);
            }
            this.InvokeAsync("DeleteFile", new object[] {
                        filePath}, this.DeleteFileOperationCompleted, userState);
        }
        
        private void OnDeleteFileOperationCompleted(object arg) {
            if ((this.DeleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileCompleted(this, new DeleteFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/CreateNewAtar", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType CreateNewAtar(string atarPath, string jsonPropFolder, string userCode) {
            object[] results = this.Invoke("CreateNewAtar", new object[] {
                        atarPath,
                        jsonPropFolder,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewAtarAsync(string atarPath, string jsonPropFolder, string userCode) {
            this.CreateNewAtarAsync(atarPath, jsonPropFolder, userCode, null);
        }
        
        /// <remarks/>
        public void CreateNewAtarAsync(string atarPath, string jsonPropFolder, string userCode, object userState) {
            if ((this.CreateNewAtarOperationCompleted == null)) {
                this.CreateNewAtarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewAtarOperationCompleted);
            }
            this.InvokeAsync("CreateNewAtar", new object[] {
                        atarPath,
                        jsonPropFolder,
                        userCode}, this.CreateNewAtarOperationCompleted, userState);
        }
        
        private void OnCreateNewAtarOperationCompleted(object arg) {
            if ((this.CreateNewAtarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewAtarCompleted(this, new CreateNewAtarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/SetPropertiesToItem", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType SetPropertiesToItem(string uploadPath, string jsonPropFolder, string userCode) {
            object[] results = this.Invoke("SetPropertiesToItem", new object[] {
                        uploadPath,
                        jsonPropFolder,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void SetPropertiesToItemAsync(string uploadPath, string jsonPropFolder, string userCode) {
            this.SetPropertiesToItemAsync(uploadPath, jsonPropFolder, userCode, null);
        }
        
        /// <remarks/>
        public void SetPropertiesToItemAsync(string uploadPath, string jsonPropFolder, string userCode, object userState) {
            if ((this.SetPropertiesToItemOperationCompleted == null)) {
                this.SetPropertiesToItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPropertiesToItemOperationCompleted);
            }
            this.InvokeAsync("SetPropertiesToItem", new object[] {
                        uploadPath,
                        jsonPropFolder,
                        userCode}, this.SetPropertiesToItemOperationCompleted, userState);
        }
        
        private void OnSetPropertiesToItemOperationCompleted(object arg) {
            if ((this.SetPropertiesToItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPropertiesToItemCompleted(this, new SetPropertiesToItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/GetPathByQuery", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType GetPathByQuery(string url, string queryStr, string userCode) {
            object[] results = this.Invoke("GetPathByQuery", new object[] {
                        url,
                        queryStr,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetPathByQueryAsync(string url, string queryStr, string userCode) {
            this.GetPathByQueryAsync(url, queryStr, userCode, null);
        }
        
        /// <remarks/>
        public void GetPathByQueryAsync(string url, string queryStr, string userCode, object userState) {
            if ((this.GetPathByQueryOperationCompleted == null)) {
                this.GetPathByQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPathByQueryOperationCompleted);
            }
            this.InvokeAsync("GetPathByQuery", new object[] {
                        url,
                        queryStr,
                        userCode}, this.GetPathByQueryOperationCompleted, userState);
        }
        
        private void OnGetPathByQueryOperationCompleted(object arg) {
            if ((this.GetPathByQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPathByQueryCompleted(this, new GetPathByQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/GetItemsByCrossSiteQuery", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType GetItemsByCrossSiteQuery(string url, string queryStr, string viewFields, uint rowLimit, string userCode) {
            object[] results = this.Invoke("GetItemsByCrossSiteQuery", new object[] {
                        url,
                        queryStr,
                        viewFields,
                        rowLimit,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsByCrossSiteQueryAsync(string url, string queryStr, string viewFields, uint rowLimit, string userCode) {
            this.GetItemsByCrossSiteQueryAsync(url, queryStr, viewFields, rowLimit, userCode, null);
        }
        
        /// <remarks/>
        public void GetItemsByCrossSiteQueryAsync(string url, string queryStr, string viewFields, uint rowLimit, string userCode, object userState) {
            if ((this.GetItemsByCrossSiteQueryOperationCompleted == null)) {
                this.GetItemsByCrossSiteQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsByCrossSiteQueryOperationCompleted);
            }
            this.InvokeAsync("GetItemsByCrossSiteQuery", new object[] {
                        url,
                        queryStr,
                        viewFields,
                        rowLimit,
                        userCode}, this.GetItemsByCrossSiteQueryOperationCompleted, userState);
        }
        
        private void OnGetItemsByCrossSiteQueryOperationCompleted(object arg) {
            if ((this.GetItemsByCrossSiteQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsByCrossSiteQueryCompleted(this, new GetItemsByCrossSiteQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/CreateDirectory", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType CreateDirectory(string url, string jsonPropFolder, string userCode) {
            object[] results = this.Invoke("CreateDirectory", new object[] {
                        url,
                        jsonPropFolder,
                        userCode});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDirectoryAsync(string url, string jsonPropFolder, string userCode) {
            this.CreateDirectoryAsync(url, jsonPropFolder, userCode, null);
        }
        
        /// <remarks/>
        public void CreateDirectoryAsync(string url, string jsonPropFolder, string userCode, object userState) {
            if ((this.CreateDirectoryOperationCompleted == null)) {
                this.CreateDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDirectoryOperationCompleted);
            }
            this.InvokeAsync("CreateDirectory", new object[] {
                        url,
                        jsonPropFolder,
                        userCode}, this.CreateDirectoryOperationCompleted, userState);
        }
        
        private void OnCreateDirectoryOperationCompleted(object arg) {
            if ((this.CreateDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDirectoryCompleted(this, new CreateDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/CreateDocLibrary1", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType CreateDocLibrary1(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            object[] results = this.Invoke("CreateDocLibrary1", new object[] {
                        url,
                        docLibName,
                        docLibUrl,
                        docLibDesc,
                        docLibTemp,
                        jsonPermissions});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDocLibrary1Async(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            this.CreateDocLibrary1Async(url, docLibName, docLibUrl, docLibDesc, docLibTemp, jsonPermissions, null);
        }
        
        /// <remarks/>
        public void CreateDocLibrary1Async(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions, object userState) {
            if ((this.CreateDocLibrary1OperationCompleted == null)) {
                this.CreateDocLibrary1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDocLibrary1OperationCompleted);
            }
            this.InvokeAsync("CreateDocLibrary1", new object[] {
                        url,
                        docLibName,
                        docLibUrl,
                        docLibDesc,
                        docLibTemp,
                        jsonPermissions}, this.CreateDocLibrary1OperationCompleted, userState);
        }
        
        private void OnCreateDocLibrary1OperationCompleted(object arg) {
            if ((this.CreateDocLibrary1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDocLibrary1Completed(this, new CreateDocLibrary1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://moch.gov.il/CreateDocLibrary", RequestNamespace="http://moch.gov.il/", ResponseNamespace="http://moch.gov.il/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnType CreateDocLibrary(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            object[] results = this.Invoke("CreateDocLibrary", new object[] {
                        url,
                        docLibName,
                        docLibUrl,
                        docLibDesc,
                        docLibTemp,
                        jsonPermissions});
            return ((ReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDocLibraryAsync(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            this.CreateDocLibraryAsync(url, docLibName, docLibUrl, docLibDesc, docLibTemp, jsonPermissions, null);
        }
        
        /// <remarks/>
        public void CreateDocLibraryAsync(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions, object userState) {
            if ((this.CreateDocLibraryOperationCompleted == null)) {
                this.CreateDocLibraryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDocLibraryOperationCompleted);
            }
            this.InvokeAsync("CreateDocLibrary", new object[] {
                        url,
                        docLibName,
                        docLibUrl,
                        docLibDesc,
                        docLibTemp,
                        jsonPermissions}, this.CreateDocLibraryOperationCompleted, userState);
        }
        
        private void OnCreateDocLibraryOperationCompleted(object arg) {
            if ((this.CreateDocLibraryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDocLibraryCompleted(this, new CreateDocLibraryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://moch.gov.il/")]
    public partial class ReturnType {
        
        private string exceptionField;
        
        private string docIDField;
        
        private int errorCodeField;
        
        private string folderPathField;
        
        private bool isSuccessField;
        
        private int docsCountField;
        
        private System.Data.DataSet dataSetField;
        
        private string errorMsgField;
        
        private string resultField;
        
        /// <remarks/>
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        public string DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FolderPath {
            get {
                return this.folderPathField;
            }
            set {
                this.folderPathField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public int DocsCount {
            get {
                return this.docsCountField;
            }
            set {
                this.docsCountField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://moch.gov.il/")]
    public enum Method {
        
        /// <remarks/>
        Get,
        
        /// <remarks/>
        Update,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SaveItemCompletedEventHandler(object sender, SaveItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SaveItemByPathCompletedEventHandler(object sender, SaveItemByPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveItemByPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveItemByPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SaveItemNoTokenCompletedEventHandler(object sender, SaveItemNoTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveItemNoTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveItemNoTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetDocumentsCompletedEventHandler(object sender, GetDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ActionsOnDocumentsCompletedEventHandler(object sender, ActionsOnDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActionsOnDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActionsOnDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ActionsOnDocumentsOldCompletedEventHandler(object sender, ActionsOnDocumentsOldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActionsOnDocumentsOldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActionsOnDocumentsOldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetReferenceNumberCompletedEventHandler(object sender, GetReferenceNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReferenceNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReferenceNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void IsLocationExistsCompletedEventHandler(object sender, IsLocationExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsLocationExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsLocationExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetDocumentByQueryCompletedEventHandler(object sender, GetDocumentByQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentByQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentByQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void MoveFileCompletedEventHandler(object sender, MoveFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DeleteFileCompletedEventHandler(object sender, DeleteFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateNewAtarCompletedEventHandler(object sender, CreateNewAtarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewAtarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewAtarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SetPropertiesToItemCompletedEventHandler(object sender, SetPropertiesToItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPropertiesToItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPropertiesToItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetPathByQueryCompletedEventHandler(object sender, GetPathByQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPathByQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPathByQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetItemsByCrossSiteQueryCompletedEventHandler(object sender, GetItemsByCrossSiteQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsByCrossSiteQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsByCrossSiteQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateDirectoryCompletedEventHandler(object sender, CreateDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateDocLibrary1CompletedEventHandler(object sender, CreateDocLibrary1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDocLibrary1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDocLibrary1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateDocLibraryCompletedEventHandler(object sender, CreateDocLibraryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDocLibraryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDocLibraryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591