//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIODATAV3.MOSS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://moch.gov.il/", ConfigurationName="MOSS.SPWebServiceSoap")]
    public interface SPWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType GetItems(string path, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetItemsAsync(string path, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SaveItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType SaveItem(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SaveItem", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SaveItemAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SaveItemByPath", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType SaveItemByPath(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SaveItemByPath", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SaveItemByPathAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SaveItemNoToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType SaveItemNoToken(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SaveItemNoToken", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SaveItemNoTokenAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType GetDocuments(string uploadPath, string queryStr, string viewFields, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetDocumentsAsync(string uploadPath, string queryStr, string viewFields, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/ActionsOnDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType ActionsOnDocuments(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/ActionsOnDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> ActionsOnDocumentsAsync(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/ActionsOnDocumentsOld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType ActionsOnDocumentsOld(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/ActionsOnDocumentsOld", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> ActionsOnDocumentsOldAsync(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetReferenceNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType GetReferenceNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetReferenceNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetReferenceNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/IsLocationExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType IsLocationExists(string pathToCheck, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/IsLocationExists", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> IsLocationExistsAsync(string pathToCheck, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetDocumentByQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType GetDocumentByQuery(string uploadPath, string queryStr, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetDocumentByQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetDocumentByQueryAsync(string uploadPath, string queryStr, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/MoveFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType MoveFile(string filepath, string despath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/MoveFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> MoveFileAsync(string filepath, string despath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/DeleteFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType DeleteFile(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/DeleteFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> DeleteFileAsync(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateNewAtar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType CreateNewAtar(string atarPath, string jsonPropFolder, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateNewAtar", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateNewAtarAsync(string atarPath, string jsonPropFolder, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SetPropertiesToItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType SetPropertiesToItem(string uploadPath, string jsonPropFolder, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/SetPropertiesToItem", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SetPropertiesToItemAsync(string uploadPath, string jsonPropFolder, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetPathByQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType GetPathByQuery(string url, string queryStr, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetPathByQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetPathByQueryAsync(string url, string queryStr, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetItemsByCrossSiteQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType GetItemsByCrossSiteQuery(string url, string queryStr, string viewFields, uint rowLimit, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/GetItemsByCrossSiteQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetItemsByCrossSiteQueryAsync(string url, string queryStr, string viewFields, uint rowLimit, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateDirectory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType CreateDirectory(string url, string jsonPropFolder, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateDirectoryAsync(string url, string jsonPropFolder, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateDocLibrary1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType CreateDocLibrary1(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateDocLibrary1", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateDocLibrary1Async(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateDocLibrary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WEBAPIODATAV3.MOSS.ReturnType CreateDocLibrary(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moch.gov.il/CreateDocLibrary", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateDocLibraryAsync(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://moch.gov.il/")]
    public partial class ReturnType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionField;
        
        private string docIDField;
        
        private int errorCodeField;
        
        private string folderPathField;
        
        private bool isSuccessField;
        
        private int docsCountField;
        
        private System.Data.DataSet dataSetField;
        
        private string errorMsgField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
                this.RaisePropertyChanged("DocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FolderPath {
            get {
                return this.folderPathField;
            }
            set {
                this.folderPathField = value;
                this.RaisePropertyChanged("FolderPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int DocsCount {
            get {
                return this.docsCountField;
            }
            set {
                this.docsCountField = value;
                this.RaisePropertyChanged("DocsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://moch.gov.il/")]
    public enum Method {
        
        /// <remarks/>
        Get,
        
        /// <remarks/>
        Update,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPWebServiceSoapChannel : WEBAPIODATAV3.MOSS.SPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPWebServiceSoapClient : System.ServiceModel.ClientBase<WEBAPIODATAV3.MOSS.SPWebServiceSoap>, WEBAPIODATAV3.MOSS.SPWebServiceSoap {
        
        public SPWebServiceSoapClient() {
        }
        
        public SPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType GetItems(string path, string userName) {
            return base.Channel.GetItems(path, userName);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetItemsAsync(string path, string userName) {
            return base.Channel.GetItemsAsync(path, userName);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType SaveItem(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            return base.Channel.SaveItem(uploadPath, filePath, jsonPropFolder, jsonPropFile, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SaveItemAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            return base.Channel.SaveItemAsync(uploadPath, filePath, jsonPropFolder, jsonPropFile, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType SaveItemByPath(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            return base.Channel.SaveItemByPath(uploadPath, filePath, jsonPropFolder, jsonPropFile, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SaveItemByPathAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile, string userCode) {
            return base.Channel.SaveItemByPathAsync(uploadPath, filePath, jsonPropFolder, jsonPropFile, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType SaveItemNoToken(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile) {
            return base.Channel.SaveItemNoToken(uploadPath, filePath, jsonPropFolder, jsonPropFile);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SaveItemNoTokenAsync(string uploadPath, string filePath, string jsonPropFolder, string jsonPropFile) {
            return base.Channel.SaveItemNoTokenAsync(uploadPath, filePath, jsonPropFolder, jsonPropFile);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType GetDocuments(string uploadPath, string queryStr, string viewFields, string userName) {
            return base.Channel.GetDocuments(uploadPath, queryStr, viewFields, userName);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetDocumentsAsync(string uploadPath, string queryStr, string viewFields, string userName) {
            return base.Channel.GetDocumentsAsync(uploadPath, queryStr, viewFields, userName);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType ActionsOnDocuments(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields) {
            return base.Channel.ActionsOnDocuments(method, url, queryStr, userCode, jsonPropFile, viewFields);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> ActionsOnDocumentsAsync(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile, string viewFields) {
            return base.Channel.ActionsOnDocumentsAsync(method, url, queryStr, userCode, jsonPropFile, viewFields);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType ActionsOnDocumentsOld(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile) {
            return base.Channel.ActionsOnDocumentsOld(method, url, queryStr, userCode, jsonPropFile);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> ActionsOnDocumentsOldAsync(WEBAPIODATAV3.MOSS.Method method, string url, string queryStr, string userCode, string jsonPropFile) {
            return base.Channel.ActionsOnDocumentsOldAsync(method, url, queryStr, userCode, jsonPropFile);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType GetReferenceNumber() {
            return base.Channel.GetReferenceNumber();
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetReferenceNumberAsync() {
            return base.Channel.GetReferenceNumberAsync();
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType IsLocationExists(string pathToCheck, string userName) {
            return base.Channel.IsLocationExists(pathToCheck, userName);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> IsLocationExistsAsync(string pathToCheck, string userName) {
            return base.Channel.IsLocationExistsAsync(pathToCheck, userName);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType GetDocumentByQuery(string uploadPath, string queryStr, string userName) {
            return base.Channel.GetDocumentByQuery(uploadPath, queryStr, userName);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetDocumentByQueryAsync(string uploadPath, string queryStr, string userName) {
            return base.Channel.GetDocumentByQueryAsync(uploadPath, queryStr, userName);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType MoveFile(string filepath, string despath) {
            return base.Channel.MoveFile(filepath, despath);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> MoveFileAsync(string filepath, string despath) {
            return base.Channel.MoveFileAsync(filepath, despath);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType DeleteFile(string filePath) {
            return base.Channel.DeleteFile(filePath);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> DeleteFileAsync(string filePath) {
            return base.Channel.DeleteFileAsync(filePath);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType CreateNewAtar(string atarPath, string jsonPropFolder, string userCode) {
            return base.Channel.CreateNewAtar(atarPath, jsonPropFolder, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateNewAtarAsync(string atarPath, string jsonPropFolder, string userCode) {
            return base.Channel.CreateNewAtarAsync(atarPath, jsonPropFolder, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType SetPropertiesToItem(string uploadPath, string jsonPropFolder, string userCode) {
            return base.Channel.SetPropertiesToItem(uploadPath, jsonPropFolder, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> SetPropertiesToItemAsync(string uploadPath, string jsonPropFolder, string userCode) {
            return base.Channel.SetPropertiesToItemAsync(uploadPath, jsonPropFolder, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType GetPathByQuery(string url, string queryStr, string userCode) {
            return base.Channel.GetPathByQuery(url, queryStr, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetPathByQueryAsync(string url, string queryStr, string userCode) {
            return base.Channel.GetPathByQueryAsync(url, queryStr, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType GetItemsByCrossSiteQuery(string url, string queryStr, string viewFields, uint rowLimit, string userCode) {
            return base.Channel.GetItemsByCrossSiteQuery(url, queryStr, viewFields, rowLimit, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> GetItemsByCrossSiteQueryAsync(string url, string queryStr, string viewFields, uint rowLimit, string userCode) {
            return base.Channel.GetItemsByCrossSiteQueryAsync(url, queryStr, viewFields, rowLimit, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType CreateDirectory(string url, string jsonPropFolder, string userCode) {
            return base.Channel.CreateDirectory(url, jsonPropFolder, userCode);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateDirectoryAsync(string url, string jsonPropFolder, string userCode) {
            return base.Channel.CreateDirectoryAsync(url, jsonPropFolder, userCode);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType CreateDocLibrary1(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            return base.Channel.CreateDocLibrary1(url, docLibName, docLibUrl, docLibDesc, docLibTemp, jsonPermissions);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateDocLibrary1Async(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            return base.Channel.CreateDocLibrary1Async(url, docLibName, docLibUrl, docLibDesc, docLibTemp, jsonPermissions);
        }
        
        public WEBAPIODATAV3.MOSS.ReturnType CreateDocLibrary(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            return base.Channel.CreateDocLibrary(url, docLibName, docLibUrl, docLibDesc, docLibTemp, jsonPermissions);
        }
        
        public System.Threading.Tasks.Task<WEBAPIODATAV3.MOSS.ReturnType> CreateDocLibraryAsync(string url, string docLibName, string docLibUrl, string docLibDesc, string docLibTemp, string jsonPermissions) {
            return base.Channel.CreateDocLibraryAsync(url, docLibName, docLibUrl, docLibDesc, docLibTemp, jsonPermissions);
        }
    }
}
